framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true

    php_errors:
        log: true

    serializer:
        enabled: true

when@test:
    framework:
        test: true